---
title: dvinebydesign
timezone: US/Arizona
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    comments: true
- scope:
    path: ''
  values:
    layout: default
    show-avatar: true
gems:
- jekyll-feed
url: http://www.dvinebydesign.com
enforce_ssl: ''
baseurl: ''
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
keywords: test1, test2, etc
desc: sample description
avatar: ''
nav-links:
  Home: "/"
  About: about
  Pricing: pricing
  Canvas: canvas
  Plexiglass: plexiglass
  Tracking: tracking
  Contact: contact
profile:
  name: David Manzer
  email: dmanzer2@gmail.com
  facebook: your-fb-id
  github: https://github.com/dmanzer2
  twitter: your-twitter-id
  linkedin: dmanzer2
  stackoverflow: dmanzer2
pretty-url: dvinebydesign.com
disqus: Your-Disqus-Id
google_analytics: Your-GA-Id
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: "/blog/:title"
sass:
  sass_dir: bower_components/bootstrap-sass/assets/stylesheets
  style: compressed
exclude:
- vendor
created-by: David Manzer
creator-url: http://www.davidmanzer.info
